"""
Step 2: Train a small CNN to predict gradient-based heatmaps from spatial features.

Input:  spatial_feat (1, C, H_s, W_s) — from MobileViTv2 backbone
Output: heatmap      (1, 1, 320, 320) — mimics HiResCAM output

The model learns to approximate the gradient-based heatmap using only
forward-pass features, so it can run on-device via ONNX without needing
backpropagation.

Usage:
  cd backend
  python train_heatmap_model.py

Requires:
  ./checkpoints/heatmap_training_data/spatial_feats.pt
  ./checkpoints/heatmap_training_data/heatmaps.pt
  (generated by generate_heatmap_data.py)

Output:
  ./checkpoints/best_heatmap_generator.pt
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, random_split
from tqdm import tqdm

# ── Configuration ─────────────────────────────────────────────────────────────

DEVICE     = torch.device("cuda" if torch.cuda.is_available() else "cpu")
BATCH_SIZE = 16
EPOCHS     = 50
LR         = 1e-3
IMG_SIZE   = 320

DATA_DIR   = "./checkpoints/heatmap_training_data"
SAVE_PATH  = "./checkpoints/best_heatmap_generator.pt"

torch.manual_seed(42)

# ── Model ─────────────────────────────────────────────────────────────────────

class HeatmapGenerator(nn.Module):
    """
    Lightweight CNN that maps spatial features → heatmap.

    Architecture:
      Conv2d (C → 128) → ReLU → Conv2d (128 → 64) → ReLU →
      Conv2d (64 → 32) → ReLU → Conv2d (32 → 1) → Sigmoid →
      Bilinear upsample to (320, 320)
    """

    def __init__(self, in_channels):
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv2d(in_channels, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),

            nn.Conv2d(128, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),

            nn.Conv2d(64, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(inplace=True),

            nn.Conv2d(32, 1, kernel_size=1),
            nn.Sigmoid(),
        )

    def forward(self, spatial_feat):
        """
        Args:
            spatial_feat: (B, C, H, W) from image backbone
        Returns:
            heatmap: (B, 1, 320, 320)
        """
        x = self.net(spatial_feat)
        x = F.interpolate(x, size=(IMG_SIZE, IMG_SIZE), mode='bilinear',
                          align_corners=False)
        return x


# ── Dataset ───────────────────────────────────────────────────────────────────

class HeatmapDataset(Dataset):
    def __init__(self, spatial_feats, heatmaps):
        self.spatial_feats = spatial_feats
        self.heatmaps = heatmaps

    def __len__(self):
        return len(self.spatial_feats)

    def __getitem__(self, idx):
        return self.spatial_feats[idx], self.heatmaps[idx]


# ── Training ──────────────────────────────────────────────────────────────────

def main():
    print(f"Device: {DEVICE}")
    print("Loading training data...")

    spatial_feats = torch.load(f"{DATA_DIR}/spatial_feats.pt", map_location="cpu")
    heatmaps = torch.load(f"{DATA_DIR}/heatmaps.pt", map_location="cpu")

    print(f"  spatial_feats: {spatial_feats.shape}")
    print(f"  heatmaps:      {heatmaps.shape}")

    in_channels = spatial_feats.shape[1]
    print(f"  in_channels:   {in_channels}")

    # Train/val split (90/10)
    dataset = HeatmapDataset(spatial_feats, heatmaps)
    n_val = max(1, int(len(dataset) * 0.1))
    n_train = len(dataset) - n_val
    train_set, val_set = random_split(dataset, [n_train, n_val],
                                       generator=torch.Generator().manual_seed(42))

    train_loader = DataLoader(train_set, batch_size=BATCH_SIZE, shuffle=True)
    val_loader = DataLoader(val_set, batch_size=BATCH_SIZE, shuffle=False)

    print(f"  train: {n_train}, val: {n_val}\n")

    # Model
    model = HeatmapGenerator(in_channels=in_channels).to(DEVICE)
    param_count = sum(p.numel() for p in model.parameters())
    print(f"HeatmapGenerator: {param_count:,} parameters\n")

    optimizer = torch.optim.Adam(model.parameters(), lr=LR)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode='min', factor=0.5, patience=5
    )
    criterion = nn.MSELoss()

    best_val_loss = float('inf')

    for epoch in range(1, EPOCHS + 1):
        # ── Train ─────────────────────────────────────────────────────────────
        model.train()
        train_loss = 0.0

        for feats, targets in tqdm(train_loader, desc=f"Epoch {epoch}/{EPOCHS}",
                                   leave=False):
            feats = feats.to(DEVICE)
            targets = targets.to(DEVICE)

            preds = model(feats)
            loss = criterion(preds, targets)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            train_loss += loss.item() * feats.size(0)

        train_loss /= n_train

        # ── Validate ──────────────────────────────────────────────────────────
        model.eval()
        val_loss = 0.0

        with torch.no_grad():
            for feats, targets in val_loader:
                feats = feats.to(DEVICE)
                targets = targets.to(DEVICE)
                preds = model(feats)
                val_loss += criterion(preds, targets).item() * feats.size(0)

        val_loss /= n_val
        scheduler.step(val_loss)

        lr_now = optimizer.param_groups[0]['lr']
        print(f"Epoch {epoch:3d} | train_loss: {train_loss:.6f} | "
              f"val_loss: {val_loss:.6f} | lr: {lr_now:.2e}")

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save({
                'model_state_dict': model.state_dict(),
                'in_channels': in_channels,
                'val_loss': best_val_loss,
            }, SAVE_PATH)
            print(f"  → Saved best model (val_loss: {best_val_loss:.6f})")

    print(f"\nTraining complete. Best val_loss: {best_val_loss:.6f}")
    print(f"Model saved to {SAVE_PATH}")


if __name__ == "__main__":
    main()
