// utils/bertTokenizer.js
//
// Minimal BERT WordPiece tokeniser for React Native.
//
// Bundled at build time via require() — no async loading needed.
// The vocab.json is generated by backend/export_for_mobile.py from the
// tokenizer.json saved alongside the fine-tuned agriculture-BERT model.
//
// Compatible with: recobo/agriculture-bert-uncased (BertTokenizer, do_lower_case=true)

const VOCAB = require("../assets/models/tokenizer/vocab.json");

// Standard BERT special-token IDs (uncased)
const PAD_ID = VOCAB["[PAD]"] ?? 0;
const UNK_ID = VOCAB["[UNK]"] ?? 100;
const CLS_ID = VOCAB["[CLS]"] ?? 101;
const SEP_ID = VOCAB["[SEP]"] ?? 102;

const MAX_CHARS  = 100;   // mirrors HuggingFace default
const MAX_LENGTH = 128;   // sequence length the ONNX model was traced with

// ── Internal helpers ──────────────────────────────────────────────────────────

function isWhitespace(cp) {
  return cp === 0x20 || cp === 0x09 || cp === 0x0a || cp === 0x0d;
}

function isControl(cp) {
  if (cp === 0x09 || cp === 0x0a || cp === 0x0d) return false; // tab, LF, CR are ok
  return (cp <= 0x1f) || (cp >= 0x7f && cp <= 0x9f);
}

function isPunctuation(cp) {
  return (cp >= 0x21 && cp <= 0x2f) ||
         (cp >= 0x3a && cp <= 0x40) ||
         (cp >= 0x5b && cp <= 0x60) ||
         (cp >= 0x7b && cp <= 0x7e);
}

/**
 * Strip control characters, normalise whitespace, lowercase.
 * Mirrors BertTokenizer's _clean_text + _tokenize_chinese_chars (skipped for English).
 */
function cleanAndLower(text) {
  let out = "";
  for (const ch of text) {
    const cp = ch.codePointAt(0);
    if (cp === 0 || cp === 0xfffd || isControl(cp)) continue;
    out += isWhitespace(cp) ? " " : ch;
  }
  return out.toLowerCase();
}

/**
 * Whitespace + punctuation tokenisation → array of word strings.
 * Mirrors BertTokenizer._run_split_on_punc + whitespace_tokenize.
 */
function basicTokenize(text) {
  const cleaned = cleanAndLower(text);
  const tokens  = [];
  let   cur     = "";

  for (const ch of cleaned) {
    const cp = ch.codePointAt(0);
    if (isWhitespace(cp)) {
      if (cur) { tokens.push(cur); cur = ""; }
    } else if (isPunctuation(cp)) {
      if (cur) { tokens.push(cur); cur = ""; }
      tokens.push(ch);
    } else {
      cur += ch;
    }
  }
  if (cur) tokens.push(cur);
  return tokens;
}

/**
 * Greedy longest-match WordPiece for a single word.
 * Returns [UNK] if the word cannot be fully decomposed.
 */
function wordpiece(word) {
  if (word.length > MAX_CHARS) return ["[UNK]"];
  if (VOCAB[word] !== undefined) return [word];

  const subtokens = [];
  let start = 0;

  while (start < word.length) {
    let end   = word.length;
    let found = null;

    while (start < end) {
      const sub = (start === 0 ? "" : "##") + word.slice(start, end);
      if (VOCAB[sub] !== undefined) { found = sub; break; }
      end--;
    }

    if (found === null) return ["[UNK]"];
    subtokens.push(found);
    start = end;
  }

  return subtokens;
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Tokenise `text` and return ONNX-ready int64 arrays for agriculture-BERT.
 *
 * @param {string} text          User's symptom description
 * @param {number} maxLength     Sequence length (default 128)
 * @returns {{ input_ids: BigInt64Array, attention_mask: BigInt64Array }}
 */
export function tokenize(text, maxLength = MAX_LENGTH) {
  const words = basicTokenize(text.trim());

  // Build token list with space reserved for [CLS] and [SEP]
  const tokenStrs = ["[CLS]"];
  for (const word of words) {
    const subs = wordpiece(word);
    tokenStrs.push(...subs);
    if (tokenStrs.length >= maxLength - 1) break; // leave room for [SEP]
  }
  tokenStrs.push("[SEP]");

  // Map strings → IDs
  const ids = tokenStrs.map((t) => VOCAB[t] ?? UNK_ID);

  // Build padded BigInt64Arrays for ONNX int64 inputs
  const input_ids      = new BigInt64Array(maxLength).fill(BigInt(PAD_ID));
  const attention_mask = new BigInt64Array(maxLength).fill(0n);

  for (let i = 0; i < Math.min(ids.length, maxLength); i++) {
    input_ids[i]      = BigInt(ids[i]);
    attention_mask[i] = 1n;
  }

  return { input_ids, attention_mask };
}
